### ISSUE TITLE
Vite suggestion

### ISSUE THREAD

**Issue by ennioVisco** [wattanx/style-resources-module#2]
Hello, thanks for working on it! 
I don't get whether for vite you are suggesting to use the vite config INSTEAD of your module, or in addition...

Could you be more clear?

**Comment by wattanx** [comment]
For vite, use vite config.
The equivalent can be achieved without this module.

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "@/assets/scss/variables.scss";',
          },
        },
      },
  }
})
```
